#pragma once
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/euler_angles.hpp>
#include <glm/gtx/string_cast.hpp>
#include <stdexcept>
#include <iostream>
#include <memory>
#include <unordered_map>
#include <cmath>
#include <vector>
#include <set>
#include <map>
#include <typeinfo>
#include <string>
#include <fstream>
#include <sstream>
#include "stb_image.h"
#define quote(x) #x
